use_frameworks!

platform :ios, '8.0'

target 'XIMTwoControllerCategoryKit_Example' do
  pod 'XIMTwoControllerCategoryKit', :path => '../'

  target 'XIMTwoControllerCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
